I am getting the following error:
Error: Build process exited with error code 1.
    at ChildProcess.<anonymous> (/layers/google.nodejs.firebasenextjs/npm_modules/node_modules/@apphosting/common/dist/index.js:36:24)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
Node.js v20.19.1"}
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51

>>Based on similar issues reported for Node.js builds using Google Cloud Buildpacks, a common reason for this specific failure pattern (exit status 1 and lifecycle status code 51) is an incompatibility between the requested Node.js version and the underlying build environment
,
. Specifically, newer Node.js versions sometimes require a newer version of the GLIBC library than what is available in the standard build container
,
. For example, Node.js v18.0.0 was reported to fail because it required GLIBC_2.28 which wasn't present in the build environment at that time
,
.
While the search results specifically mention issues with Node.js v18.0.0
,
, it is highly probable that your attempt to use Node.js v20.19.1 is encountering a similar incompatibility issue within the Firebase Studio build environment.

using this information try debugging and resolving the issue